-- Bulk import of content requests from marketing pipeline sheet
-- Generated from 'Marketing pipeline bluck content - Sheet2.csv'
-- Review before running. Rows flagged NO-DATE below use a placeholder date (today)
-- because the sheet had neither a Post Date nor Internal Deadline for them.
--
-- Owner/Requester rule: Internal requirement rows -> Manish, Organic rows -> Satya
-- (resolved by email against profiles, so no hardcoded UUIDs). PM rows keep the
-- owner/requester already baked into their JSON below.
--
-- NOTE: REQ-006 (Individuial ads for Wise 8,HB+ for the display at hop): NO DATE in sheet — placeholder 2026-07-14 used, please fix in-app
-- NOTE: REQ-007 (Nutrition Quote (Hygiene post for Hop)): NO DATE in sheet — placeholder 2026-07-14 used, please fix in-app
-- NOTE: REQ-009 (AI achieveing peak health): NO DATE in sheet — placeholder 2026-07-14 used, please fix in-app
-- NOTE: REQ-010 (Plantar Fasciitis): NO DATE in sheet — placeholder 2026-07-14 used, please fix in-app

do $$
begin
  if (select id from profiles where email = 'manish.kumar@hbplus.fit') is null then
    raise exception 'No profiles row for %  -- has Manish logged into the app yet?', 'manish.kumar@hbplus.fit';
  end if;
  if (select id from profiles where email = 'satya.choudhury@hbplus.fit') is null then
    raise exception 'No profiles row for %  -- has Satya logged into the app yet?', 'satya.choudhury@hbplus.fit';
  end if;
end $$;

with resolved as (
  select (select id from profiles where email = 'manish.kumar@hbplus.fit') as manish_id,
         (select id from profiles where email = 'satya.choudhury@hbplus.fit') as satya_id
),
raw_rows (id, data) as (
  values
    ('REQ-001', '{"id": "REQ-001", "title": "Test one", "brief": "for the tes pupose", "pipeline": "PM", "status": "Brief Approval", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": ["2063cbac-17e4-4296-a9af-ccfdb3448497"], "followerIds": [], "reviewerIds": ["2063cbac-17e4-4296-a9af-ccfdb3448497"], "postDate": "2026-07-12T00:00:00.000Z", "internalDeadline": "2026-07-07T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": ["https://content.hbplus.fit/"], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-10T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-002', '{"id": "REQ-002", "title": "What if ''I dont fit in....'' carousel", "brief": "", "pipeline": "Organic", "status": "Posted", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-18T00:00:00.000Z", "internalDeadline": "2026-07-13T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-003', '{"id": "REQ-003", "title": "Video for Hop display", "brief": "This video will  show multuiple event clips that we do", "pipeline": "Internal requirement", "status": "Design Review", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-14T00:00:00.000Z", "internalDeadline": "2026-07-02T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-004', '{"id": "REQ-004", "title": "Physio led rehabh and training", "brief": "This is an banner for the pikel ball court", "pipeline": "Internal requirement", "status": "Posted", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-10T00:00:00.000Z", "internalDeadline": "2026-07-08T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-02T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-005', '{"id": "REQ-005", "title": "Ads for HB+ app", "brief": "In app ads for app", "pipeline": "Internal requirement", "status": "Posted", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-08T00:00:00.000Z", "internalDeadline": "2026-07-08T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-06T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-006', '{"id": "REQ-006", "title": "Individuial ads for Wise 8,HB+ for the display at hop", "brief": "This will be an ad video for wise 8 and HB+", "pipeline": "Internal requirement", "status": "Brief Approval", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-14T00:00:00.000Z", "internalDeadline": "2026-07-14T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-007', '{"id": "REQ-007", "title": "Nutrition Quote (Hygiene post for Hop)", "brief": "", "pipeline": "Organic", "status": "Posted", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-14T00:00:00.000Z", "internalDeadline": "2026-07-14T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-008', '{"id": "REQ-008", "title": "Physio vs. Chiro", "brief": "", "pipeline": "Organic", "status": "Posted", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-16T00:00:00.000Z", "internalDeadline": "2026-07-11T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-009', '{"id": "REQ-009", "title": "AI achieveing peak health", "brief": "\"Slide 1 (Hook / Misdirection)\n\nThis is how AI helped me achieve my peak health.\nSwipe to check the 3 prompts that actually work.\n\nSlide 2 (Generate subhadeep''s image for this bit)\nWhy did you swipe? Seriously? AI is the \"\"Health Expert\"\" you go to?\n\nSlide 3\nAI can guide you.\nBut it can''t really know you.\n\nIt doesn''t know your body, your habits,\nor why you skip workouts on certain days.\nIt can give you answers-\nbut only if you ask the right questions.\nAnd most people don''t.\n\nSo before you rely on AI for your health,\nPut this workflow to your life\n\nSlide 3\nTake a step back and understand where you are right now.\n\nAsk yourself. What are you actually trying to improve?\nFat loss, strength, better energy, or just feeling less tired?\nBecause if the goal isn''t clear,\nnothing else will be.\n\nStart with something measurable, realistic, and personal to you.\n\n\"", "pipeline": "Organic", "status": "Design Progress", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-14T00:00:00.000Z", "internalDeadline": "2026-07-14T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": ["https://www.instagram.com/p/DWtPbjHiPWk/?igsh=amd4dWd6ODJpNjF4"], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-010', '{"id": "REQ-010", "title": "Plantar Fasciitis", "brief": "", "pipeline": "Organic", "status": "Design", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-14T00:00:00.000Z", "internalDeadline": "2026-07-14T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-011', '{"id": "REQ-011", "title": "Gym vs HB+ Carousel", "brief": "\"Slide 1: If Netflix can reach your home...\nSlide 2: If groceries can reach your home...\nSlide 3: If doctors can reach your home...\nSlide 4: If meetings can reach your home...\n\nSlide 5: Why are we still travelling for workouts?  Traffic and Distance are just another non-reasons, that shouldn''t come in the way of your selfcare journey. \"", "pipeline": "Organic", "status": "Design", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-23T00:00:00.000Z", "internalDeadline": "2026-07-18T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-012', '{"id": "REQ-012", "title": "Hush n Heal (July)", "brief": "", "pipeline": "Organic", "status": "Design Progress", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-14T00:00:00.000Z", "internalDeadline": "2026-07-09T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb),
    ('REQ-013', '{"id": "REQ-013", "title": "Childhood Pictures (EGC Reel)", "brief": "", "pipeline": "Organic", "status": "Brief Approval", "requesterId": "10fdd038-55a0-4874-844f-3dea0c12145d", "ownerId": "10fdd038-55a0-4874-844f-3dea0c12145d", "assigneeIds": [], "followerIds": [], "reviewerIds": [], "postDate": "2026-07-18T00:00:00.000Z", "internalDeadline": "2026-07-13T00:00:00.000Z", "daysNeeded": 3, "rounds": [{"round": 0, "comments": [], "status": "pending", "submissionLinks": [], "submissionNote": ""}], "currentRound": 0, "attachments": [], "referenceLinks": [], "approvedAt": null, "approvedBy": [], "createdAt": "2026-07-14T00:00:00.000Z", "postDateHistory": [], "creatorRemovedFromApproval": false, "managerApproved": false, "founderApprovalRequired": false, "founderApproved": false, "activityLog": [], "postedBy": [], "assigneeAcceptance": [], "initiatedAt": null, "category": null}'::jsonb)
)
insert into content_requests (id, data, updated_at)
select
  r.id,
  jsonb_set(
    jsonb_set(
      r.data,
      '{ownerId}',
      to_jsonb(case r.data->>'pipeline'
        when 'Internal requirement' then resolved.manish_id::text
        when 'Organic'              then resolved.satya_id::text
        else r.data->>'ownerId'
      end)
    ),
    '{requesterId}',
    to_jsonb(case r.data->>'pipeline'
      when 'Internal requirement' then resolved.manish_id::text
      when 'Organic'              then resolved.satya_id::text
      else r.data->>'requesterId'
    end)
  ),
  now()
from raw_rows r, resolved
on conflict (id) do update set data = excluded.data, updated_at = excluded.updated_at;
